### PR TITLE
Fix and improve DraggableStructure

### LINKED ISSUE #1702: Floating molecule and local state ?
There is an issue with floating molecule. You can click twice to edit the molecule from the floating molecule which is nice but while the molecule is correctly changed in the panel, the floating molecule is not changed (local state ???).

Each molecule must have a unique ID and the floating molecule should only have this uniqueID as property. If the molecule is deleted this uniqueID will disappear and the floating molecule will disappear as well. If the molecule is edited it should be refreshed automatically.

This should be done after: https://github.com/cheminfo/nmrium/issues/1700

### PR DESCRIPTION
**Pull request by stropitek**
Closes #1702

### CODE REVIEW

**Comment by stropitek** [comment]
@wadjih-bencheikh18 can you take over this PR and work on the state refactor:

Create new property `view.floatingMolecules` in the main state of the application (which comes from `ChartContext`)

The new state is structured like this:
```ts
Array<{
  id: string; // reference to the id in `molecules`
  visible: boolean; // If the floating molecule is shown
}>
```

and it should replace the `isFloat` state in `molecules`

**Comment by wadjih-bencheikh18** [comment]
@stropitek i don't have access to push in this branch, do you want me to create new PR?

**Comment by stropitek** [comment]
> i don't have access to push in this branch, do you want me to create new PR?

Yes please do so

**Comment by wadjih-bencheikh18** [comment]
> Yes please do so

new PR created you can delete this PR

File: src/component/reducer/Reducer.ts [hunk 1]
```diff
@@ -85,6 +85,7 @@ export const getInitialState = (): State => ({
   activeSpectrum: null,
   mode: 'RTL',
   molecules: [],
+  floatingMolecules: [],
```
Comment (lpatiny) [inline src/component/reducer/Reducer.ts:88]: @stropitek I think this property should not be at the first level but rather in another prop 'view' or something like that. WDYT ?

**Comment by lpatiny** [comment]
The functionality is ok. If we edit the molecule it correctly change the floating molecule as well. I think however there is a level missing in the state to store all the 'view' related information.

File: src/component/reducer/Reducer.ts (hunk 1 above)
Comment (stropitek) [reply src/component/reducer/Reducer.ts:88]: Let's but in a `view` property, it will help identify what has already been identified as not belonging to the core data state.

**Comment by stropitek** [comment]
Good work @wadjih-bencheikh18 👍🏻 

I can't really tell what changed in the tests from this but the implementation LGTM

**Comment by stropitek** [comment]
Just change the datastructure to add the `view` level and we can merge this

**Comment by wadjih-bencheikh18** [comment]
> change the datastructure to add the `view` level

Could you please explain this, Do you mean NMRiumData ?

**Comment by stropitek** [comment]
> Could you please explain this, Do you mean NMRiumData ?

No I'm referring to the unresolved conversation: https://github.com/cheminfo/nmrium/pull/1715#discussion_r953680900

It just that `floatingMolecules` should not be at the first level of the state, but in a `view` property.

**Comment by lpatiny** [comment]
there is still a problem with the toggle button to display the molecule. When we close the molecule the button does toggle.

**Comment by wadjih-bencheikh18** [comment]
> When we close the molecule the button does toggle.

I will fix it now and add the test case,
Thank you

**Comment by wadjih-bencheikh18** [comment]
I added new element named `ActiveButton` (not sure about the name) that allow toggle btn and the style change depend `value` prop
