### PR TITLE
fix(ranges): do not edit assignment without signal

### LINKED ISSUE #4061: Trying to assign a range without a signal throws an error
From here: https://github.com/cheminfo/nmrium/blob/fe2f0321256feba5eb04163215d039a5751f0ad0/src/component/panels/RangesPanel/TableColumns/SignalAssignmentColumn.tsx#L25

This whole table is really not type-safe.

### PR DESCRIPTION
**Pull request by targos**
Improve type safety around ranges table and handle absence of signal. Also fixes inconsistencies in the edition of numbers (delta ppm).

Closes: https://github.com/cheminfo/nmrium/issues/4061

### CODE REVIEW

File: src/component/reducer/actions/RangesActions.ts [hunk 1]
```diff
@@ -315,7 +315,7 @@ function handleChangeRangeSignalKind(
 
   const rangeIndex = getRangeIndex(spectrum, range.id);
   const _range = spectrum.ranges.values[rangeIndex];
-  if (_range?.signals) {
+  if (_range.signals && range.tableMetaInfo.signalIndex) {
```
Comment (stropitek) [inline src/component/reducer/actions/RangesActions.ts]: Can `signalIndex` be 0? Then the check might be wrong.

**Review by stropitek — APPROVED** [review]

File: src/component/reducer/actions/RangesActions.ts (hunk 1 above)
Comment (targos) [reply src/component/reducer/actions/RangesActions.ts]: probably, good catch!
